/**
 * POST /api/reset
 *
 * Wipes all generated / user content so the playground returns to a
 * true blank-template state:
 *
 *   • Figma credentials  (.figma-config.json)
 *   • Design tokens      (styles/generated-tokens.css, styles/schemes.css)
 *   • Docs               (docs/design.md, docs/tokens.json, docs/import-meta.json)
 *   • Built components   (components/*.tsx + *.module.css, except ui/)
 *   • Barrel file        (components/index.ts → empty)
 *   • Preview pages      (app/preview/component/**)
 *
 * The client side (ResetHandler) clears branch-namespaced localStorage
 * after this endpoint returns.
 */

import { NextResponse } from "next/server";
import fs   from "fs";
import path from "path";

const CWD = process.cwd();

// ── Paths ──────────────────────────────────────────────────────────────────────
const FIGMA_CONFIG       = path.join(CWD, ".figma-config.json");
const TOKENS_CSS         = path.join(CWD, "styles", "generated-tokens.css");
const SCHEMES_CSS        = path.join(CWD, "styles", "schemes.css");
const DESIGN_MD          = path.join(CWD, "docs", "design.md");
const TOKENS_JSON        = path.join(CWD, "docs", "tokens.json");
const IMPORT_META        = path.join(CWD, "docs", "import-meta.json");
const COMPONENTS_DIR     = path.join(CWD, "components");
const BARREL_PATH        = path.join(COMPONENTS_DIR, "index.ts");
const PREVIEW_COMPONENT  = path.join(CWD, "app", "preview", "component");

const EMPTY_BARREL = `// Auto-generated barrel — updated by /api/components on every scan.\n// Do not edit manually.\nexport {};\n`;
const EMPTY_SCHEMES = `/* schemes.css — generated by Figma import. */\n`;

// ── Helpers ────────────────────────────────────────────────────────────────────
function tryUnlink(filePath: string) {
  try { if (fs.existsSync(filePath)) fs.unlinkSync(filePath); } catch { /* ok */ }
}

function tryRmDir(dirPath: string) {
  try {
    if (fs.existsSync(dirPath)) fs.rmSync(dirPath, { recursive: true, force: true });
  } catch { /* ok */ }
}

// ── Route ──────────────────────────────────────────────────────────────────────
export async function POST() {
  // 1. Figma credentials
  tryUnlink(FIGMA_CONFIG);

  // 2. Generated token / doc files
  tryUnlink(TOKENS_CSS);
  tryUnlink(DESIGN_MD);
  tryUnlink(TOKENS_JSON);
  tryUnlink(IMPORT_META);

  // 3. Reset schemes.css to an empty placeholder (file must exist for CSS imports)
  try { fs.writeFileSync(SCHEMES_CSS, EMPTY_SCHEMES, "utf8"); } catch { /* ok */ }

  // 4. Delete built components (everything in /components except ui/ and index.ts)
  try {
    if (fs.existsSync(COMPONENTS_DIR)) {
      for (const entry of fs.readdirSync(COMPONENTS_DIR)) {
        if (entry === "ui" || entry === "index.ts") continue;
        const full = path.join(COMPONENTS_DIR, entry);
        const stat = fs.statSync(full);
        if (stat.isDirectory()) tryRmDir(full);
        else tryUnlink(full);
      }
    }
  } catch { /* ok */ }

  // 5. Reset barrel to empty
  try { fs.writeFileSync(BARREL_PATH, EMPTY_BARREL, "utf8"); } catch { /* ok */ }

  // 6. Delete all auto-generated preview pages
  try {
    if (fs.existsSync(PREVIEW_COMPONENT)) {
      for (const entry of fs.readdirSync(PREVIEW_COMPONENT)) {
        tryRmDir(path.join(PREVIEW_COMPONENT, entry));
      }
    }
  } catch { /* ok */ }

  return NextResponse.json({ ok: true });
}
