/**
 * /api/components — list all built components in /components/ AND sync routing.
 *
 * Scans /components/ for PascalCase .tsx files, returns the list, and:
 *   1. Atomically rewrites components/index.ts (barrel)
 *   2. Generates app/preview/component/[Name]/page.tsx per component
 *   3. Upserts playground-owned sections in AGENTS.md (creates the file if absent)
 *
 * Each generated preview page uses a DIRECT import of its component file —
 * bypassing Turbopack's static barrel cache so newly built components render
 * immediately without a server restart.
 *
 * GET /api/components
 * → { components: Array<{ componentName: string }> }
 */

import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

const COMPONENTS_DIR   = path.join(process.cwd(), "components");
const BARREL_PATH      = path.join(COMPONENTS_DIR, "index.ts");
const PREVIEW_BASE_DIR = path.join(process.cwd(), "app", "preview", "component");
const AGENTS_PATH      = path.join(process.cwd(), "AGENTS.md");

// ── AGENTS.md section definitions ────────────────────────────────────────────
//
// Each entry owns a BEGIN/END block in AGENTS.md.  The route upserts these
// sections on every scan so a new project gets the rules automatically and an
// existing project always stays in sync with the playground's conventions.
// Any content outside the markers is never touched.

const AGENTS_SECTIONS: Array<{ id: string; content: string }> = [
  {
    id: "nextjs-agent-rules",
    content: `# This is NOT the Next.js you know

This version has breaking changes — APIs, conventions, and file structure may all differ from your training data. Read the relevant guide in \`node_modules/next/dist/docs/\` before writing any code. Heed deprecation notices.`,
  },
  {
    id: "component-placement-rules",
    content: `# Built component file placement

When building a new component for the playground, files MUST go here:

| File | Location |
|---|---|
| Component | \`/components/{ComponentName}.tsx\` |
| CSS module | \`/components/{ComponentName}.module.css\` |

**Never place built components in \`/app/components/\`** — that directory contains playground infrastructure (Playground, BuildPanel, WorkBench, etc.) and is never scanned for built components.

**Never manually create a preview page.** The route \`/api/components\` scans \`/components/\` and auto-generates \`/app/preview/component/{Name}/page.tsx\` on every call. The playground calls this automatically.

**Never manually edit \`/components/index.ts\`.** That barrel file is also auto-generated by \`/api/components\`.

# Built component authoring rules

**Exports (required):**
- Use a named export: \`export function ComponentName(...)\`
- Do NOT use \`export default\`
- Export the color scheme: \`export const defaultScheme = "{scheme-name}" as const;\`
  Set the scheme to match the Figma frame (e.g. \`"light"\`, \`"dark"\`)

**Color scheme:**
- Do NOT put \`data-scheme\` on the component's root element
- The playground wraps the component in a \`SchemeProvider\` that applies \`data-scheme\` via a \`display:contents\` ancestor — no scheme hook or override logic is needed in the component
- Do NOT import or use \`useSchemeOverride\`

**"use client" directive:**
- Add \`"use client"\` ONLY if the component uses React hooks (\`useState\`, \`useEffect\`, \`useRef\`, etc.) or browser APIs
- Pure presentational components that receive all data via props do NOT need \`"use client"\`
- Do NOT add \`"use client"\` just for scheme handling

**Component imports:**
- Use UI primitives from \`@/components/ui/\` (buttons, inputs, etc.) where they apply
- Do NOT import other built components from \`/components/\`

**Tokens and responsive behavior:**
- Design system tokens handle fluid sizing via CSS container query units — apply them automatically
- Only add \`@container\` or \`@media\` rules if the layout structure itself changes at a breakpoint`,
  },
];

/**
 * Upserts playground-owned BEGIN/END sections in AGENTS.md.
 * Creates the file from the sections if it doesn't exist.
 * Any content outside the markers is preserved unchanged.
 */
function syncAgentsMd(): void {
  let existing = "";
  try {
    existing = fs.readFileSync(AGENTS_PATH, "utf8");
  } catch {
    // File doesn't exist yet — will be created below
  }

  let result = existing;

  for (const { id, content } of AGENTS_SECTIONS) {
    const begin = `<!-- BEGIN:${id} -->`;
    const end   = `<!-- END:${id} -->`;
    const block = `${begin}\n${content}\n${end}`;

    const startIdx = result.indexOf(begin);
    const endIdx   = result.indexOf(end);

    if (startIdx !== -1 && endIdx !== -1) {
      // Replace existing section
      result = result.slice(0, startIdx) + block + result.slice(endIdx + end.length);
    } else {
      // Append new section (with a blank line separator if file has content)
      result = result ? `${result.trimEnd()}\n\n${block}\n` : `${block}\n`;
    }
  }

  try {
    fs.writeFileSync(AGENTS_PATH, result, "utf8");
  } catch {
    // Non-fatal — AGENTS.md update failed
  }
}

// Only surface PascalCase .tsx files — these are built components
const COMPONENT_FILE_RE = /^([A-Z][A-Za-z0-9]*)\.tsx$/;

/** Generate the content of a per-component preview page. */
// Canonical background colours for each scheme name.
// Used by the preview page so it gets the right background even before the
// design system's schemes.css is populated with full token overrides.
const SCHEME_BACKGROUNDS: Record<string, string> = {
  "light": "#ffffff",
  "dark":  "#1a1a1a",
};

function buildPreviewPage(name: string, hasDefaultScheme: boolean): string {
  const schemeImport = hasDefaultScheme
    ? `import { ${name}, defaultScheme as componentDefaultScheme } from "../../../../components/${name}";`
    : `import { ${name} } from "../../../../components/${name}";`;

  const activeScheme = hasDefaultScheme
    ? `const activeScheme = (scheme as SchemeName | undefined) ?? componentDefaultScheme;`
    : `const activeScheme = scheme as SchemeName | undefined;`;

  // Serialise the lookup table so the generated page can resolve the bg at runtime.
  const bgMapLiteral = JSON.stringify(SCHEME_BACKGROUNDS);

  // Canvas background is always pinned to the component's defaultScheme —
  // the scheme dropdown changes token values inside the component only,
  // not the surrounding preview canvas.
  const bgLine = hasDefaultScheme
    ? `const bg = SCHEME_BG[componentDefaultScheme] ?? "#ffffff";`
    : `const bg = "#ffffff";`;

  return `// Auto-generated by /api/components — do not edit manually.
// Re-generated on every /api/components scan so the import always reflects
// the current component file directly (bypasses Turbopack barrel caching).
export const dynamic = "force-dynamic";

${schemeImport}
import { SchemeProvider, type SchemeName } from "../../../components/SchemeContext";

const SCHEME_BG: Record<string, string> = ${bgMapLiteral};

export default async function ${name}Preview({
  searchParams,
}: {
  searchParams: Promise<{ scheme?: string }>;
}) {
  const { scheme } = await searchParams;
  ${activeScheme}

  ${bgLine}

  const rootStyle: React.CSSProperties = {
    containerType: "inline-size",
    containerName: "pg-root",
    width: "100%",
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: bg,
  };

  return (
    <SchemeProvider scheme={activeScheme}>
      <div style={rootStyle}>
        <${name} />
      </div>
    </SchemeProvider>
  );
}
`;
}

export async function GET() {
  if (!fs.existsSync(COMPONENTS_DIR)) {
    return NextResponse.json({ components: [] });
  }

  let files: string[];
  try {
    files = fs.readdirSync(COMPONENTS_DIR);
  } catch {
    return NextResponse.json({ components: [] });
  }

  const names = files
    .map((f) => COMPONENT_FILE_RE.exec(f)?.[1])
    .filter((n): n is string => !!n);

  // ── 1. Sync barrel ───────────────────────────────────────────────────────────
  // Rebuild index.ts from scratch so it always matches the filesystem exactly —
  // no duplicates, no stale entries, no manual register step required.
  const schemeMap: Record<string, boolean> = {};
  try {
    const lines = [
      "// Auto-generated barrel — updated by /api/components on every scan.",
      "// Do not edit manually.",
      "export {};", // ensures this is always a valid TS module even when empty
    ];

    for (const name of names) {
      const src = fs.readFileSync(path.join(COMPONENTS_DIR, `${name}.tsx`), "utf8");
      const hasDefaultScheme = /export\s+const\s+defaultScheme\s*=/.test(src);
      schemeMap[name] = hasDefaultScheme;
      lines.push(
        hasDefaultScheme
          ? `export { ${name}, defaultScheme as ${name}DefaultScheme } from "./${name}";`
          : `export { ${name} } from "./${name}";`,
      );
    }

    fs.writeFileSync(BARREL_PATH, lines.join("\n") + "\n", "utf8");
  } catch {
    // Non-fatal — barrel update failed, populate schemeMap from what we have
    for (const name of names) {
      if (!(name in schemeMap)) {
        try {
          const src = fs.readFileSync(path.join(COMPONENTS_DIR, `${name}.tsx`), "utf8");
          schemeMap[name] = /export\s+const\s+defaultScheme\s*=/.test(src);
        } catch {
          schemeMap[name] = false;
        }
      }
    }
  }
  // ────────────────────────────────────────────────────────────────────────────

  // ── 2. Generate per-component preview pages ──────────────────────────────────
  // Each page has a DIRECT import so Turbopack compiles it fresh — no barrel
  // caching. The iframe in Playground.tsx points to /preview/component/[Name].
  try {
    fs.mkdirSync(PREVIEW_BASE_DIR, { recursive: true });

    for (const name of names) {
      const dir = path.join(PREVIEW_BASE_DIR, name);
      fs.mkdirSync(dir, { recursive: true });
      const pageContent = buildPreviewPage(name, schemeMap[name] ?? false);
      fs.writeFileSync(path.join(dir, "page.tsx"), pageContent, "utf8");
    }
  } catch {
    // Non-fatal — preview pages failed to generate
  }
  // ────────────────────────────────────────────────────────────────────────────

  // ── 3. Sync AGENTS.md ────────────────────────────────────────────────────────
  // Upserts playground-owned BEGIN/END sections so a new project always gets
  // the correct authoring rules without any manual setup step.
  syncAgentsMd();
  // ────────────────────────────────────────────────────────────────────────────

  const components = names.map((componentName) => ({ componentName }));
  return NextResponse.json({ components });
}
