// Main preview route — reserved for future use.
// Individual components are rendered at /preview/component/{Name}
// which is auto-generated by /api/components on each scan.
export default function Preview() {
  return null;
}
